BEGIN;

ALTER TABLE users 
DROP CONSTRAINT IF EXISTS possible_status, 
DROP CONSTRAINT IF EXISTS status_deleted, 
DROP CONSTRAINT IF EXISTS status_suspended, 
DROP COLUMN IF EXISTS is_superuser, 
DROP COLUMN IF EXISTS status, 
DROP COLUMN IF EXISTS deleted_at, 
DROP COLUMN IF EXISTS suspended_at;

COMMIT;