// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup_queries.sql

package repository

import (
	"context"
)

const cleanupExpiredMfaMail = `-- name: CleanupExpiredMfaMail :exec
DELETE FROM mfa_mail 
WHERE expires_at<NOW()
`

func (q *Queries) CleanupExpiredMfaMail(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredMfaMail)
	return err
}

const cleanupExpiredMfaSessions = `-- name: CleanupExpiredMfaSessions :exec
DELETE FROM mfa_session 
WHERE expires_at<NOW()
`

func (q *Queries) CleanupExpiredMfaSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredMfaSessions)
	return err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM sessions 
WHERE expires_at<NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}
