// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identifier_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getIdentifierByMfaSession = `-- name: GetIdentifierByMfaSession :one
SELECT user_id FROM mfa_session 
WHERE mfa_session_token=$1
`

func (q *Queries) GetIdentifierByMfaSession(ctx context.Context, mfaSessionToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIdentifierByMfaSession, mfaSessionToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getIdentifierByRefresh = `-- name: GetIdentifierByRefresh :one
SELECT s.user_id FROM refresh_tokens rt
JOIN sessions s ON rt.session_id=s.id
WHERE rt.refresh_token=$1
`

func (q *Queries) GetIdentifierByRefresh(ctx context.Context, refreshToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIdentifierByRefresh, refreshToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getIdentifierBySession = `-- name: GetIdentifierBySession :one
SELECT user_id FROM sessions 
WHERE session_token=$1
`

func (q *Queries) GetIdentifierBySession(ctx context.Context, sessionToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIdentifierBySession, sessionToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getIdentifierByUsernameOrEmail = `-- name: GetIdentifierByUsernameOrEmail :one
SELECT id, username, email FROM users 
WHERE username=$1 OR email=$1
`

type GetIdentifierByUsernameOrEmailRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) GetIdentifierByUsernameOrEmail(ctx context.Context, username string) (GetIdentifierByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getIdentifierByUsernameOrEmail, username)
	var i GetIdentifierByUsernameOrEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}
