// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkVerificationCode = `-- name: CheckVerificationCode :one
SELECT code FROM mfa_mail 
WHERE id=$1 AND mfa_type=$2 AND expires_at > NOW()
`

type CheckVerificationCodeParams struct {
	ID      uuid.UUID `json:"id"`
	MfaType string    `json:"mfa_type"`
}

func (q *Queries) CheckVerificationCode(ctx context.Context, arg CheckVerificationCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, checkVerificationCode, arg.ID, arg.MfaType)
	var code string
	err := row.Scan(&code)
	return code, err
}

const clearMfaMail = `-- name: ClearMfaMail :execrows
DELETE FROM mfa_mail 
WHERE id=$1
`

func (q *Queries) ClearMfaMail(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearMfaMail, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEmail = `-- name: CountEmail :one
SELECT COUNT(*) FROM users 
WHERE email=$1
`

func (q *Queries) CountEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsername = `-- name: CountUsername :one
SELECT COUNT(*) FROM users 
WHERE username=$1
`

func (q *Queries) CountUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMfaMail = `-- name: CreateMfaMail :one
INSERT INTO mfa_mail (user_id, mfa_type, code, expires_at) 
VALUES ($1, $2, $3, $4) 
ON CONFLICT (user_id, mfa_type) 
DO UPDATE 
SET code = EXCLUDED.code, 
    expires_at = EXCLUDED.expires_at, 
    created_at = now()
RETURNING id
`

type CreateMfaMailParams struct {
	UserID    uuid.UUID `json:"user_id"`
	MfaType   string    `json:"mfa_type"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMfaMail(ctx context.Context, arg CreateMfaMailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMfaMail,
		arg.UserID,
		arg.MfaType,
		arg.Code,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, mfa) 
VALUES ($1, $2, $3, $4) 
RETURNING id
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Mfa          bool   `json:"mfa"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Mfa,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCookieSession = `-- name: DeleteCookieSession :one
DELETE FROM sessions 
WHERE id=$1 
RETURNING user_id
`

func (q *Queries) DeleteCookieSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCookieSession, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteJWTSession = `-- name: DeleteJWTSession :execrows
DELETE FROM sessions 
WHERE id=$1 AND user_id=$2
`

type DeleteJWTSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteJWTSession(ctx context.Context, arg DeleteJWTSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJWTSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM refresh_tokens 
WHERE session_id=$1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users 
WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findUserByUsernameOrEmail = `-- name: FindUserByUsernameOrEmail :one
SELECT id, username, email FROM users 
WHERE username=$1 OR email=$1
`

type FindUserByUsernameOrEmailRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) FindUserByUsernameOrEmail(ctx context.Context, username string) (FindUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsernameOrEmail, username)
	var i FindUserByUsernameOrEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const getSessionIdAndCsrf = `-- name: GetSessionIdAndCsrf :one
SELECT id, csrf_token FROM sessions 
WHERE session_token=$1 AND expires_at > NOW()
`

type GetSessionIdAndCsrfRow struct {
	ID        uuid.UUID `json:"id"`
	CsrfToken string    `json:"csrf_token"`
}

func (q *Queries) GetSessionIdAndCsrf(ctx context.Context, sessionToken string) (GetSessionIdAndCsrfRow, error) {
	row := q.db.QueryRow(ctx, getSessionIdAndCsrf, sessionToken)
	var i GetSessionIdAndCsrfRow
	err := row.Scan(&i.ID, &i.CsrfToken)
	return i, err
}

const getSessionIdByRefresh = `-- name: GetSessionIdByRefresh :one
SELECT session_id FROM refresh_tokens 
WHERE refresh_token=$1 AND expires_at > NOW()
`

func (q *Queries) GetSessionIdByRefresh(ctx context.Context, refreshToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionIdByRefresh, refreshToken)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getUserByIdOrUsername = `-- name: GetUserByIdOrUsername :one
SELECT id, username, email, password_hash, email_verified, mfa FROM users 
WHERE username=$1 OR id=$2
`

type GetUserByIdOrUsernameParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

type GetUserByIdOrUsernameRow struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	Mfa           bool      `json:"mfa"`
}

func (q *Queries) GetUserByIdOrUsername(ctx context.Context, arg GetUserByIdOrUsernameParams) (GetUserByIdOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdOrUsername, arg.Username, arg.ID)
	var i GetUserByIdOrUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Mfa,
	)
	return i, err
}

const getUserIdBySession = `-- name: GetUserIdBySession :one
SELECT user_id FROM sessions 
WHERE session_token=$1 AND expires_at > NOW()
`

func (q *Queries) GetUserIdBySession(ctx context.Context, sessionToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIdBySession, sessionToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserIdBySessionId = `-- name: GetUserIdBySessionId :one
SELECT user_id FROM sessions 
WHERE id=$1 AND expires_at > NOW()
`

func (q *Queries) GetUserIdBySessionId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIdBySessionId, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertCookieSession = `-- name: InsertCookieSession :one
INSERT INTO sessions (user_id, session_token, csrf_token, platform, expires_at) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id
`

type InsertCookieSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	SessionToken string    `json:"session_token"`
	CsrfToken    string    `json:"csrf_token"`
	Platform     string    `json:"platform"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) InsertCookieSession(ctx context.Context, arg InsertCookieSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCookieSession,
		arg.UserID,
		arg.SessionToken,
		arg.CsrfToken,
		arg.Platform,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertJWTSession = `-- name: InsertJWTSession :one
INSERT INTO sessions (user_id, platform, expires_at) 
VALUES ($1, $2, $3) 
RETURNING id
`

type InsertJWTSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Platform  string    `json:"platform"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertJWTSession(ctx context.Context, arg InsertJWTSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertJWTSession, arg.UserID, arg.Platform, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (session_id, refresh_token, expires_at) 
VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.SessionID, arg.RefreshToken, arg.ExpiresAt)
	return err
}

const updateCookieSession = `-- name: UpdateCookieSession :execrows
UPDATE sessions 
SET session_token=$1, csrf_token=$2, expires_at=$3 
WHERE id=$4 AND expires_at > NOW()
`

type UpdateCookieSessionParams struct {
	SessionToken string    `json:"session_token"`
	CsrfToken    string    `json:"csrf_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCookieSession(ctx context.Context, arg UpdateCookieSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCookieSession,
		arg.SessionToken,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJWTSession = `-- name: UpdateJWTSession :execrows
UPDATE sessions 
SET expires_at=$1 
WHERE id=$2
`

type UpdateJWTSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateJWTSession(ctx context.Context, arg UpdateJWTSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJWTSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execrows
UPDATE refresh_tokens 
SET refresh_token=$1, expires_at=$2 
WHERE refresh_token=$3 AND session_id=$4 AND expires_at > NOW()
`

type UpdateRefreshTokenParams struct {
	RefreshToken   string    `json:"refresh_token"`
	ExpiresAt      time.Time `json:"expires_at"`
	RefreshToken_2 string    `json:"refresh_token_2"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRefreshToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshToken_2,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
