// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearAllSessions = `-- name: ClearAllSessions :execrows
DELETE FROM sessions 
WHERE user_id=$1
`

func (q *Queries) ClearAllSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearAllSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCookieSession = `-- name: DeleteCookieSession :execrows
DELETE FROM sessions 
WHERE id=$1
`

func (q *Queries) DeleteCookieSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCookieSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJWTSession = `-- name: DeleteJWTSession :execrows
DELETE FROM sessions 
WHERE id=$1
`

func (q *Queries) DeleteJWTSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJWTSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionIdAndCsrf = `-- name: GetSessionIdAndCsrf :one
SELECT id, csrf_token FROM sessions 
WHERE session_token=$1 AND expires_at>NOW()
`

type GetSessionIdAndCsrfRow struct {
	ID        uuid.UUID `json:"id"`
	CsrfToken string    `json:"csrf_token"`
}

func (q *Queries) GetSessionIdAndCsrf(ctx context.Context, sessionToken string) (GetSessionIdAndCsrfRow, error) {
	row := q.db.QueryRow(ctx, getSessionIdAndCsrf, sessionToken)
	var i GetSessionIdAndCsrfRow
	err := row.Scan(&i.ID, &i.CsrfToken)
	return i, err
}

const getSessionIdByRefresh = `-- name: GetSessionIdByRefresh :one
SELECT session_id FROM refresh_tokens 
WHERE refresh_token=$1 AND expires_at>NOW()
`

func (q *Queries) GetSessionIdByRefresh(ctx context.Context, refreshToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionIdByRefresh, refreshToken)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getUserIdBySessionId = `-- name: GetUserIdBySessionId :one
SELECT user_id FROM sessions 
WHERE id=$1 AND expires_at>NOW()
`

func (q *Queries) GetUserIdBySessionId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIdBySessionId, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertCookieSession = `-- name: InsertCookieSession :one
INSERT INTO sessions (user_id, session_token, csrf_token, platform, expires_at) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id
`

type InsertCookieSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	SessionToken string    `json:"session_token"`
	CsrfToken    string    `json:"csrf_token"`
	Platform     string    `json:"platform"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) InsertCookieSession(ctx context.Context, arg InsertCookieSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCookieSession,
		arg.UserID,
		arg.SessionToken,
		arg.CsrfToken,
		arg.Platform,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertJWTSession = `-- name: InsertJWTSession :one
INSERT INTO sessions (user_id, platform, expires_at) 
VALUES ($1, $2, $3) 
RETURNING id
`

type InsertJWTSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Platform  string    `json:"platform"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertJWTSession(ctx context.Context, arg InsertJWTSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertJWTSession, arg.UserID, arg.Platform, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (session_id, refresh_token, expires_at) 
VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.SessionID, arg.RefreshToken, arg.ExpiresAt)
	return err
}

const updateCookieSession = `-- name: UpdateCookieSession :execrows
UPDATE sessions 
SET session_token=$1, csrf_token=$2, expires_at=$3 
WHERE id=$4 AND expires_at>NOW()
`

type UpdateCookieSessionParams struct {
	SessionToken string    `json:"session_token"`
	CsrfToken    string    `json:"csrf_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCookieSession(ctx context.Context, arg UpdateCookieSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCookieSession,
		arg.SessionToken,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJWTSession = `-- name: UpdateJWTSession :execrows
UPDATE sessions 
SET expires_at=$1 
WHERE id=$2 AND expires_at>NOW()
`

type UpdateJWTSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateJWTSession(ctx context.Context, arg UpdateJWTSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJWTSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execrows
UPDATE refresh_tokens 
SET refresh_token=$1, expires_at=$2 
WHERE refresh_token=$3 AND session_id=$4 AND expires_at>NOW()
`

type UpdateRefreshTokenParams struct {
	RefreshToken   string    `json:"refresh_token"`
	ExpiresAt      time.Time `json:"expires_at"`
	RefreshToken_2 string    `json:"refresh_token_2"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRefreshToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshToken_2,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
