// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFirstSuperuser = `-- name: CreateFirstSuperuser :execrows
INSERT INTO users (username, email, password_hash, is_superuser, mfa, email_verified) 
VALUES ($1, $2, $3, true, true, true)
ON CONFLICT DO NOTHING
`

type CreateFirstSuperuserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateFirstSuperuser(ctx context.Context, arg CreateFirstSuperuserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFirstSuperuser, arg.Username, arg.Email, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, mfa) 
VALUES ($1, $2, $3, $4) 
RETURNING id
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Mfa          bool   `json:"mfa"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Mfa,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email=$1
)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findUserByUsernameOrEmail = `-- name: FindUserByUsernameOrEmail :one
SELECT id, username, email FROM users 
WHERE username=$1 OR email=$1
`

type FindUserByUsernameOrEmailRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) FindUserByUsernameOrEmail(ctx context.Context, username string) (FindUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsernameOrEmail, username)
	var i FindUserByUsernameOrEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const getSuperuserStatus = `-- name: GetSuperuserStatus :one
SELECT is_superuser from users 
WHERE id=$1
`

func (q *Queries) GetSuperuserStatus(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getSuperuserStatus, id)
	var is_superuser bool
	err := row.Scan(&is_superuser)
	return is_superuser, err
}

const getUserById = `-- name: GetUserById :one
SELECT username, email, password_hash, mfa FROM users 
WHERE id=$1
`

type GetUserByIdRow struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Mfa          bool   `json:"mfa"`
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Mfa,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, password_hash, email_verified, status, suspended_at, suspended_for, deleted_at, mfa FROM users 
WHERE username=$1 OR email=$1
`

type GetUserByUsernameOrEmailRow struct {
	ID            uuid.UUID     `json:"id"`
	Username      string        `json:"username"`
	Email         string        `json:"email"`
	PasswordHash  string        `json:"password_hash"`
	EmailVerified bool          `json:"email_verified"`
	Status        string        `json:"status"`
	SuspendedAt   time.Time     `json:"suspended_at"`
	SuspendedFor  time.Duration `json:"suspended_for"`
	DeletedAt     time.Time     `json:"deleted_at"`
	Mfa           bool          `json:"mfa"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (GetUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, username)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Status,
		&i.SuspendedAt,
		&i.SuspendedFor,
		&i.DeletedAt,
		&i.Mfa,
	)
	return i, err
}

const getUserIdBySession = `-- name: GetUserIdBySession :one
SELECT user_id FROM sessions 
WHERE session_token=$1 AND expires_at>NOW()
`

func (q *Queries) GetUserIdBySession(ctx context.Context, sessionToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIdBySession, sessionToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const hardDeleteUser = `-- name: HardDeleteUser :execrows
DELETE FROM users 
WHERE id=$1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteSuperuser = `-- name: PromoteSuperuser :execrows
UPDATE users 
SET is_superuser=true, updated_at=NOW() 
WHERE id=$1
`

func (q *Queries) PromoteSuperuser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteSuperuser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviveUser = `-- name: ReviveUser :execrows
UPDATE users 
SET status='active', deleted_at=NULL, suspended_at=NULL, suspended_for=NULL 
WHERE id=$1
`

func (q *Queries) ReviveUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reviveUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users 
SET status='deleted', deleted_at=NOW() 
WHERE id=$1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspendUser = `-- name: SuspendUser :execrows
UPDATE users 
SET status='suspended', suspended_at=NOW(), suspended_for=$2 
WHERE id=$1
`

type SuspendUserParams struct {
	ID           uuid.UUID     `json:"id"`
	SuspendedFor time.Duration `json:"suspended_for"`
}

func (q *Queries) SuspendUser(ctx context.Context, arg SuspendUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendUser, arg.ID, arg.SuspendedFor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users 
SET password_hash=$1, updated_at=$2 
WHERE id=$3
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE username=$1
)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
