// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkMfaSession = `-- name: CheckMfaSession :one
SELECT user_id FROM mfa_session 
WHERE mfa_session_token=$1 AND expires_at>NOW()
`

func (q *Queries) CheckMfaSession(ctx context.Context, mfaSessionToken string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkMfaSession, mfaSessionToken)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const clearMfaSessions = `-- name: ClearMfaSessions :execrows
DELETE FROM mfa_session 
WHERE user_id=$1
`

func (q *Queries) ClearMfaSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearMfaSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeVerificationCode = `-- name: ConsumeVerificationCode :one
DELETE FROM mfa_mail 
WHERE id=$1 AND mfa_type=$2 AND code=$3 AND expires_at>NOW() 
RETURNING user_id
`

type ConsumeVerificationCodeParams struct {
	ID      uuid.UUID `json:"id"`
	MfaType string    `json:"mfa_type"`
	Code    string    `json:"code"`
}

func (q *Queries) ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeVerificationCode, arg.ID, arg.MfaType, arg.Code)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createMfaMail = `-- name: CreateMfaMail :one
INSERT INTO mfa_mail (user_id, mfa_type, code, expires_at) 
VALUES ($1, $2, $3, $4) 
ON CONFLICT (user_id, mfa_type) 
DO UPDATE 
SET code=EXCLUDED.code, 
    expires_at=EXCLUDED.expires_at, 
    created_at=NOW()
RETURNING id
`

type CreateMfaMailParams struct {
	UserID    uuid.UUID `json:"user_id"`
	MfaType   string    `json:"mfa_type"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMfaMail(ctx context.Context, arg CreateMfaMailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMfaMail,
		arg.UserID,
		arg.MfaType,
		arg.Code,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMfaSession = `-- name: CreateMfaSession :exec
INSERT INTO mfa_session (user_id, mfa_session_token, expires_at) 
VALUES ($1, $2, $3)
`

type CreateMfaSessionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	MfaSessionToken string    `json:"mfa_session_token"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreateMfaSession(ctx context.Context, arg CreateMfaSessionParams) error {
	_, err := q.db.Exec(ctx, createMfaSession, arg.UserID, arg.MfaSessionToken, arg.ExpiresAt)
	return err
}

const verifyEmail = `-- name: VerifyEmail :execrows
UPDATE users 
SET email_verified=true, updated_at=NOW() 
WHERE id=$1
`

func (q *Queries) VerifyEmail(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, verifyEmail, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
